Added response and diagnosis words as in fep_reset page
acisops/acis_anomaly_pages pull request #12
Opened 2017-05-26 14:35 UTC by richardjedgar

Minor changes to response and diagnosis words, to match the fep_reset page.

Dunno why the diffs don't show up?

2017-05-26 14:43 UTC, Gregg140 commented
You might have to change the branch you are looking at as I cloned from 
a branch and not Master.

Try fep_reset_may2017


On 05/26/2017 10:35 AM, richardjedgar wrote:
>
> Minor changes to response and diagnosis words, to match the fep_reset 
> page.
>
> Dunno why the diffs don't show up?
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/acisops/acis_anomaly_pages/pull/12
>
>
>         Commit Summary
>
>   * Added response and diagnosis words as in fep_reset page
>
>
>         File Changes
>
>   * *A* dea_seq_reset.rst
>     <https://github.com/acisops/acis_anomaly_pages/pull/12/files#diff-0>
>     (97)
>
>
>         Patch Links:
>
>   * https://github.com/acisops/acis_anomaly_pages/pull/12.patch
>   * https://github.com/acisops/acis_anomaly_pages/pull/12.diff
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub 
> <https://github.com/acisops/acis_anomaly_pages/pull/12>, or mute the 
> thread 
> <https://github.com/notifications/unsubscribe-auth/ABpcCi0DIki5m3wz9H59IPz-fjnV0jsnks5r9uMwgaJpZM4NnrPM>.
>

2017-05-26 15:01 UTC, jzuhone commented
@richardjedgar it looks like you added a new file to the top-level directory in `acis_anomaly_pages` when you should have edited the `dea_seq_reset.rst` in the `source` subdirectory. 

Probably the best thing to do is make the edits on that latter file, delete the new file you made (`git rm`), and push up the changes to this branch and PR. Everything else here is fine.

2017-05-26 15:07 UTC, richardjedgar commented
Ah. Thanks. Hopefully it's fixed now.

2017-06-19 19:57 UTC, jzuhone requested changes

2017-06-19 19:57 UTC, jzuhone commented on source/dea_seq_reset.rst
> +case of :ref:`fep_reset`.
Change :ref:`fep_reset` to :doc:`../fep_reset` here to fix the broken link.

2017-06-19 20:02 UTC, richardjedgar commented on source/dea_seq_reset.rst
> +case of :ref:`fep_reset`.
no backticks?

2017-06-19 20:03 UTC, jzuhone commented on source/dea_seq_reset.rst
> +case of :ref:`fep_reset`.
sorry, yes, backticks around the ../fep_reset part. unfortunately it doesn't render correctly in here.

2017-06-19 20:06 UTC, jzuhone approved these changes

2017-06-19 20:34 UTC, richardjedgar commented
@cegrant approved by e-mail.

2017-06-19 20:42 UTC, richardjedgar commented
Paul approved by e-mail

2017-06-27 19:38 UTC, Gregg140 commented
Looks good to me.

2017-06-27 19:38 UTC, merged